"""empty message

Revision ID: 5e341fe659a4
Revises: 8e313f9057ca
Create Date: 2025-01-17 03:13:39.344982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e341fe659a4"
down_revision: Union[str, None] = "8e313f9057ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("chat_id", sa.BigInteger(), nullable=False)
    )
    op.create_index(
        op.f("ix_users_chat_id"), "users", ["chat_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_chat_id"), table_name="users")
    op.drop_column("users", "chat_id")
    # ### end Alembic commands ###
